# .github/workflows/main.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/release.yml
    secrets:
      APPLICATION_ACCESS_TOKEN: ${{ secrets.APPLICATION_ACCESS_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}