name: Runs On Pull Request

on: [pull_request]

jobs:
  prerelease:
    uses: ./.github/workflows/prerelease.yml
    secrets:
      APPLICATION_ACCESS_TOKEN: ${{ secrets.APPLICATION_ACCESS_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}