# .github/workflows/reusable-deploy-package.yml
name: Deploy Release Package

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '18.17'
      runs_on:
        description: 'github runner operating system image version'
        default: 'ubuntu-latest'
        required: false
        type: string
      registry_url:
        required: false
        type: string
        default: 'https://npm.pkg.github.com'
    secrets:
      APPLICATION_ACCESS_TOKEN:
        description: 'GitHub Access Token'
        required: true
      NPM_TOKEN:
        description: 'NPM Token'
        required: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release_packages:
    name: Package Release
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ inputs.node_version }}
          registry-url: ${{ inputs.registry_url }}

      - name: Install Dependencies
        run: npm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.APPLICATION_ACCESS_TOKEN }}

      - name: Build
        run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.APPLICATION_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.APPLICATION_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.APPLICATION_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.APPLICATION_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
